#!/bin/sh
#
# xencommons    Script to start DomD guest
#
# Author:       Andrii Anisov <andrii_anisov@epam.com>
#
# chkconfig: 2345 70 10
# description: Starts and stops drivers domain (DomD)
### BEGIN INIT INFO
# Provides:          guest_domd
# Required-Start:    $xenstored $xenconsoled
# Should-Start:
# Required-Stop:     $xenstored $xenconsoled
# Should-Stop:
# Default-Start:     2 3 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop DomD
# Description:       Starts and stops drivers domain (DomD)
### END INIT INFO

DOMAIN_NAME="DomD"
CONFIG_NAME="domd.cfg"
CONFIG_PATH="/xt/dom.cfg"

# not running in Xen dom0 or domU
if ! test -d /proc/xen ; then
        exit 0
fi

do_start () {
    echo "Starting ${DOMAIN_NAME}"
    if xl domid ${DOMAIN_NAME} &> /dev/null; then
        echo "${DOMAIN_NAME} is already running"
        exit 0
    fi
    xl create ${CONFIG_PATH}/${CONFIG_NAME}
}

do_stop () {
    echo "Stopping ${DOMAIN_NAME}"

    if ! xl domid ${DOMAIN_NAME} &> /dev/null ; then
        echo "${DOMAIN_NAME} is not running"
        exit 0
    fi
    xl destroy ${DOMAIN_NAME}
}

do_status () {
    if ! xl domid ${DOMAIN_NAME} &> /dev/null ; then
        echo "${DOMAIN_NAME} is not running"
        exit 0
    else
        xl list ${DOMAIN_NAME}
    fi
}

case "$1" in
  start)
        do_start
        ;;
  status)
        do_status
        ;;
  stop)
        do_stop
        ;;
  reload)
        echo >&2 'Reload not available; use force-reload'; exit 1
        ;;
  force-reload|restart)
        do_stop
        do_start
        ;;
  *)
        # do not advertise unreasonable commands that there is no reason
        # to use with this device
        echo $"Usage: $0 {start|stop|status|restart|force-reload}"
        exit 1
esac

exit $?
